this.list = [
  // TEMPLE [-1]
  { name:"staticBox",
    position:[31,-11,-1],
    inItem:"Simple Boots",
    spriteNr:2,
  },
  { name:"Table",
    position:[31,-12,-1],
  },
  { name:"Simple Boots",
    position:[31,-12,-1],
    pickable: false
  },
  { name:"staticBox",
    position:[31,-7,-1],
    inItem: "Rod",
    spriteNr:2,
  },
  { name:"Table",
    position:[31,-6,-1],
  },
  { name:"Rod",
    position:[31,-6,-1],
    pickable: false
  },
  { name:"staticBox",
    position:[38,-11,-1],
    inItem: "Backpack",
    spriteNr:2,
  },
  { name:"Table",
    position:[38,-12,-1],
  },
  { name:"Backpack",
    position:[38,-12,-1],
    pickable: false
  },

  // TEMPLE [0]
  { name:"Table",
    position:[30,-13,0],
  },
  { name:"Locker",
    position:[30,-13,0],
    spriteNr:6,
  },
  { name:"Table",
    position:[31,-13,0],
  },
  { name:"Table",
    position:[32,-13,0],
  },
  { name:"Locker",
    position:[32,-13,0],
    spriteNr:6,
  },
  { name:"Table",
    position:[34,-13,0],
  },
  { name:"Locker",
    position:[34,-13,0],
    spriteNr:6,
  },
  { name:"Table",
    position:[35,-13,0],
  },
  { name:"Table",
    position:[36,-13,0],
  },
  { name:"Locker",
    position:[36,-13,0],
    spriteNr:6,
  },
  { name:"Table",
    position:[38,-13,0],
  },
  { name:"Locker",
    position:[38,-13,0],
    spriteNr:6,
  },

  // NORTH OF CASTLE [ladder]
  { name:"staticBox",
    position:[50,-40,0],
    spriteNr:2,
    inItem: "Ladder"
  },
  // TOWER 
  { name:"staticBox",
    position:[44,-38,4],
    spriteNr:2,
    inItem: "Random Item"
  },
  // KING's QUEST
  { name:"staticBox",
    position:[56,-20,-1],
    spriteNr:2,
    inItem: "Simple Helmet"
  },
  { name:"Simple Helmet",
    position:[57,-20,-1]
  },
  { name:"staticBox",
    position:[56,-24,-2],
    spriteNr:2,
    inItem: "Wand of Destiny"
  },
  { name:"Wand of Destiny",
    position:[56,-25,-2]
  },
  // CASTLEGATE
  { name:"Ladder",
    position:[32,-23,0],
  },
  { name:"Ladder",
    position:[33,-24,1],
  },
  // CASTLEGATE NORTH 
  { name:"Ladder",
    position:[33,-47,1],
  },

  // CYCLOPS QUEST
  { name:"staticBox",
    position:[90,4,1],
    inItem: "Simple Legs"
  },
  // DRAGON QUEST
  { name:"staticBox",
    position:[138,-1,0],
    inItem: "Simple Armor"
  },
  { name:"staticBox",
    spriteNr:2,
    position:[146,6,1],
    inItem: "King Armor"
  },
  // WIZARD QUEST
  { name:"staticBox",
    position:[-68,14,-1],
    inItem: "Magic Armor",
  },
  { name:"staticBox",
    position:[-71,13,3],
    inItem: "Magic Hat",
    spriteNr:2,
  },

  // DEPO [-1] - TRAINS
  { name:"staticBox",
    position:[49,8,-1],
    level:0,
    spriteNr:2,
    inItem: "Simple Shield"
  },
  { name:"Simple Shield",
    position:[49,9,-1]
  },

  // DEPO [0]
  { name:"Table",
    position:[42,6,0],
  },
  { name:"Locker",
    position:[42,6,0],
  },
  { name:"Table",
    position:[43,6,0],
  },
  { name:"Table",
    position:[44,6,0],
  },
  { name:"Locker",
    position:[44,6,0],
  },
  { name:"Table",
    position:[46,6,0],
  },
  { name:"Locker",
    position:[46,6,0],
  },
  { name:"Table",
    position:[47,6,0],
  },
  { name:"Table",
    position:[48,6,0],
  },
  { name:"Locker",
    position:[48,6,0],
  },
   

  // DEPO [1] CHESTS
  { name:"staticBox",
    position:[42,-2,1],
    inItem: "King Legs",
    level:100
  },
  { name:"Table",
    position:[41,-2,1],
  },
  { name:"King Legs",
    position:[41,-2,1]
  },
  { name:"staticBox",
    position:[42,0,1],
    inItem: "King Boots",
    level:150
  },
  { name:"Table",
    position:[41,0,1],
  },
  { name:"King Boots",
    position:[41,0,1]
  },
  { name:"staticBox",
    position:[42,2,1],
    inItem: "Blessed Shield",
    level:200
  },
  { name:"Table",
    position:[41,2,1],
  },
  { name:"Blessed Shield",
    position:[41,2,1]
  },
  { name:"staticBox",
    position:[42,4,1],
    inItem: "The Crown",
    level:250
  },
  { name:"Table",
    position:[41,4,1],
  },
  { name:"The Crown",
    position:[41,4,1]
  },
  { name:"Table",
    position:[46,5,1],
  },
  { name:"Locker",
    position:[46,5,1],
  },
  { name:"Table",
    position:[47,5,1],
  },
  { name:"Table",
    position:[48,5,1],
  },
  { name:"Locker",
    position:[48,5,1],
  },

  // WIZARDS
  { name:"Wand of Destiny",
    position:[-72,11,2]
  },
  { name:"Magic Hat",
    position:[-71,10,2]
  },
  { name:"Magic Armor",
    position:[-71,11,2]
  },

  // BLUE 17
  { name:"Ladder",
    position:[25,15,1],
  },
  { name:"staticBox",
    position:[29,13,1],
    inItem: "Coins",
    spriteNr:2,
  },
]